project_region: us-central1
vertex_project: smart-ads-451319
vertex_bucket: gs://vertexai_inputfiles
cache: False
input_data_path: gs://first_vertex_ai_kfp_1/fake_dataset.csv
container_image: us-central1-docker.pkg.dev/smart-ads-451319/randomforest-vertexai/randomforest_vertexai:20250719-164335
location: us-central1
artefacts_bucket: vertexai_output_models
project_id: smart-ads-451319
